database:
  master:
    driver: "mysql"
    name: "blog"
    host: "localhost"
    port: "60029"
    user: "root"
    password: "root"
    maxopen: 50
    maxidle: 10
    maxlifetime: 3
  slave:
    driver: "mysql"
    name: "blog"
    host: "localhost"
    port: "60029"
    user: "root"
    password: "root"
    maxopen: 50
    maxidle: 10
    maxlifetime: 3

app:
  env: "local"
  dbDebug: "true"
  apiPrefix: "blog"
  apiKey: "thisisapikey"

server:
  port: "80"

gcloud:
  projectid: 

consumers:


publishers:

    
cron:
