version: "3.7"
networks:
  net-dev:
    driver: bridge
services:
  mysql:
    container_name: mysql
    image: arm64v8/mysql:oracle
    command: --authentication-policy=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=blog
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "60029:3306"
    networks:
      - net-dev
volumes:
  mysql-data: